### PR TITLE
r/virtual_machine: Handle missing environment browser

### LINKED ISSUE #411: unexpected EOF when running example template
### Terraform Version

Terraform v0.11.3
+ provider.vsphere v1.3.2

### vSphere Provider Version

$ terraform providers
.
└── provider.vsphere

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

Based on template from https://www.terraform.io/docs/providers/vsphere/index.html

```hcl
provider "vsphere" {
  user           = "<user>"
  password       = "<password>"
  vsphere_server = "<ip>"

  # if you have a self-signed cert
  allow_unverified_ssl = true

  client_debug = true
}

data "vsphere_datacenter" "dc" {
  name = "Cloud-DC"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "Cluster-1/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }
}
```

### Crash Output

```
Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


panic: runtime error: invalid memory address or nil pointer dereference
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf79f13]
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: goroutine 193 [running]:
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere/inter$
al/helper/computeresource.DefaultDevicesFromReference(0xc42053a070, 0xc4205bc220, 0x16, 0xc4205a5390, 0xa, 0xc420014fe0, 0x13, 0x0, 0x0, 0x0, ...)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terrafor$
-providers/terraform-provider-vsphere/vsphere/internal/helper/computeresource/compute_resource_helper.go:146 +0x1c3
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere/inter$
al/helper/resourcepool.DefaultDevices(0xc42053a070, 0xc420302040, 0xc420014fe0, 0x13, 0xc4202db0f0, 0xc42049f540, 0xc, 0xc42050d4b4, 0xa)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terrafor$
-providers/terraform-provider-vsphere/vsphere/internal/helper/resourcepool/resource_pool_helper.go:116 +0x229
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.resou$
ceVSphereVirtualMachineCreateBare(0xc4205ba3f0, 0x1206180, 0xc42016cf40, 0x11760e0, 0xc420143c00, 0x0)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terrafor$
-providers/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:674 +0x971
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.resou$
ceVSphereVirtualMachineCreate(0xc4205ba3f0, 0x1206180, 0xc42016cf40, 0x24, 0x20f8160)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/[37/1849]
-providers/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machine.go:219 +0x4af
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.
com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc42014a690, 0xc42007a140, 0xc420143800, 0x1206180, 0xc42016cf40, 0x1, 0xc42058c2a0, 0xc420068de0
)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform
-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:227 +0x364
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.
com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42014ad90, 0xc42007a050, 0xc42007a140, 0xc420143800, 0x7f5c5c67c640, 0x0, 0x18)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform
-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.
com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4201429e0, 0xc420142780, 0xc4202da240, 0x0, 0x0)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform
-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: reflect.Value.call(0xc4200688a0, 0xc42018c070, 0x13, 0x148d15f, 0x4, 0xc
42027bf20, 0x3, 0x3, 0x403a23, 0xc42053c000, ...)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /usr/local/go/src/reflect/value.go:434 +0x905
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: reflect.Value.Call(0xc4200688a0, 0xc42018c070, 0x13, 0xc42003ef20, 0x3,
0x3, 0xc42003ef20, 0xc42003ef28, 0xc420354080)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /usr/local/go/src/reflect/value.go:302 +0xa4
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: net/rpc.(*service).call(0xc420558140, 0xc42055e050, 0xc42036a1b8, 0xc420
376000, 0xc420143300, 0x11237e0, 0xc420142780, 0x16, 0x1123820, 0xc4202da240, ...)
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /usr/local/go/src/net/rpc/server.go:381 +0x142
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: created by net/rpc.(*Server).ServeCodec
2018-02-23T16:29:13.043-0800 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:       /usr/local/go/src/net/rpc/server.go:475 +0x36b
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalWriteState
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalIf
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalWriteState
2018-02-23T16:29:13.046-0800 [DEBUG] plugin: plugin process exited: path=/usr/local/google/home/rdc/go/src/k8s.io/kube-deploy/cluster-api-gcp/cloud/terraf
orm/templates/vmware/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.3.2_x4
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalWriteDiff
2018/02/23 16:29:13 [TRACE] root: eval: *terraform.EvalApplyPost
2018/02/23 16:29:13 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.vm: unexpected EOF
2018/02/23 16:29:13 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.vm: unexpected EOF
2018/02/23 16:29:13 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.vm
2018/02/23 16:29:13 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/02/23 16:29:13 [TRACE] dag/walk: upstream errored, not walking "provider.vsphere (close)"
2018/02/23 16:29:13 [TRACE] dag/walk: upstream errored, not walking "root"
2018/02/23 16:29:13 [TRACE] Preserving existing state lineage "e64226d1-582d-4051-acfb-f7cff06660bb"
2018/02/23 16:29:13 [TRACE] Preserving existing state lineage "e64226d1-582d-4051-acfb-f7cff06660bb"
2018/02/23 16:29:13 [TRACE] Preserving existing state lineage "e64226d1-582d-4051-acfb-f7cff06660bb"
2018/02/23 16:29:13 [TRACE] Preserving existing state lineage "e64226d1-582d-4051-acfb-f7cff06660bb"
2018/02/23 16:29:13 [DEBUG] plugin: waiting for all plugin processes to complete...
2018-02-23T16:29:13.056-0800 [WARN ] plugin: error closing client during Kill: err="connection is shut down"



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Expected Behavior

Crashed

### Actual Behavior

I would have expected the VM creation or some better error message.

### Steps to Reproduce

1. `terraform apply .`

### PR DESCRIPTION
**Pull request by vancluever**
The virtual machine resource relies on the cluster or standalone host
it's deployed on for information regarding a default hardware set or
guest OS family information. This is obtained via the `EnvironmentBrowser`
MO referenced by the respective cluster or host's `ComputeResource` MO.

There are certain situations where this attribute will be missing, two
of which have been identified so far via bug reports:

* A cluster without hosts will not contain an environment browser.
* vSphere licensing issues may cause a missing environment browser (#409
reported an expired vCenter).

This update wraps our fetching of the environment browser by the two
current compute resource helpers that utilize it in a helper that
validates that we actually have an environment browser before proceeding
to load it up, issuing an error alluding to the above if it is missing.

Fixes #411.
May also correct #409.

### CODE REVIEW

File: vsphere/resource_vsphere_virtual_machine_test.go [hunk 1]
```diff
@@ -8088,3 +8129,188 @@ resource "vsphere_virtual_machine" "vm" {
...
+  disk {
+    label = "disk0"
+    size  = 20
+  }
+}
+`,
+		os.Getenv("VSPHERE_DATACENTER"),
+		os.Getenv("VSPHERE_EMPTY_CLUSTER"),
+		os.Getenv("VSPHERE_NETWORK_LABEL_PXE"),
+		os.Getenv("VSPHERE_DATASTORE"),
```
Comment (paddycarver) [inline vsphere/resource_vsphere_virtual_machine_test.go]: nit: these functions feel like they'd be more reusable if the environment variables are passed in as arguments, but I don't have the context to know if that's a valid design consideration or not.

File: vsphere/resource_vsphere_virtual_machine_test.go [hunk 2]
```diff
@@ -1028,6 +1048,27 @@ func TestAccResourceVSphereVirtualMachine(t *testing.T) {
...
+				Providers: testAccProviders,
+				Steps: []resource.TestStep{
+					{
+						Config:      testAccResourceVSphereVirtualMachineConfigCloneEmptyCluster(),
+						ExpectError: regexp.MustCompile("compute resource .* is missing an Environment Browser\\. Check host, cluster, and vSphere license health of all associated resources and try again"),
+						PlanOnly:    true,
+					},
+					{
+						Config: testAccResourceVSphereEmpty,
+						Check:  resource.ComposeTestCheckFunc(),
```
Comment (paddycarver) [inline vsphere/resource_vsphere_virtual_machine_test.go]: Is this really supposed to execute the config and not check anything?

File: vsphere/resource_vsphere_virtual_machine_test.go (hunk 1 above)
Comment (vancluever) [reply vsphere/resource_vsphere_virtual_machine_test.go]: Where applicable, configuration generators do have parameterization, but again, only when it's necessary in a test (ie: a multi-step test where the configuration is the same but a variable is changing). Otherwise, these configurations should be considered static and doubling up the parameterization would only serve to make things more redundant.

Some future work I'm considering doing is possibly adding to the test suite so that we can load external configuration (ie: out of a `test-fixtures` directory), and allowing the use of actual variables. If that indeed comes to fruition, this is probably when I would come back to this and refactor things so that the parameterization is in the individual test cases themselves.

Comment (tombuildsstuff) [reply vsphere/resource_vsphere_virtual_machine_test.go]: on that note - tbh there's an argument for making these values a Struct that's parsed out once, rather than in each test function (this is the case in all providers)

File: vsphere/resource_vsphere_virtual_machine_test.go (hunk 2 above)
Comment (vancluever) [reply vsphere/resource_vsphere_virtual_machine_test.go]: This is necessary for steps with `PlanOnly` to ensure that the destroy step does not attempt to plan/refresh off of the broken configuration and run into the same issue. I think this might be a bug in the test framework but I'm not 100% sure, as the destroy step is only supposed to run if a state exists as referenced [here](https://github.com/hashicorp/terraform/blob/master/helper/resource/testing.go#L566). and it's odd to me as to why a bad plan would have a state versus a bad apply. In any case, the second step just runs with a completely blank config to clear out the state so any subsequent destroy steps have nothing to do.

An example of what happens when that step does not run:

```
    --- FAIL: TestAccResourceVSphereVirtualMachine/clone_into_empty_cluster,_no_environment_browser_(fails_on_plan) (5.54s)
    	testing.go:573: Error destroying resource! WARNING: Dangling resources
    		may exist. The full state and error is shown below.
    		
    		Error: Error refreshing: 1 error(s) occurred:
    		
    		* vsphere_virtual_machine.vm: 1 error(s) occurred:
    		
    		* vsphere_virtual_machine.vm: cannot find OS family for guest ID "ubuntu64Guest": compute resource "ComputeResource:domain-c178 @ /hashi-dc/host/hashi-cluster2" is missing an Environment Browser. Check host, cluster, and vSphere license health of all associated resources and try again
    		
    		State: <nil>
```

I've removed it from the apply test (creation from scratch) and will push.

File: vsphere/resource_vsphere_virtual_machine_test.go (hunk 1 above)
Comment (vancluever) [reply vsphere/resource_vsphere_virtual_machine_test.go]: I would be fine with this if there was a way to wrap it in a way that retains the same "static generation" look and feel. I actually am not a fan of having variables declared in _every_ test function.

I think that something along the lines of this would work even:

```
Config: resource.GenerateConfig(testAccResourceVSphereConfigHere),
```

Where `resource.GenerateConfig` is a generator that takes a `text/template` with a lightweight, Packer-ish way of accessing environment variables.

```go
testAccSomeConfig = `
variable "foo" {
  default = "{{env TEST_PROVDER_ENV_VAR}}"
}
`
```

In any case, such things are kind of out of scope here :stuck_out_tongue:

**Comment by vancluever** [comment]
Thanks @paddycarver!

**Comment by paddycarver** [comment]
(This approval was meant to convey "looks good to me within the limits of my ability to determine whether something is good or not", but I've been awful at communicating today, so apologies if it came off as something else.)
